version: '3'
services:
  #授权服务
  hanying_spider:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_spider:latest
    container_name: hanying_spider
    restart: always
    ports:
      - 8608:8608
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_spider
    volumes:
      - ../log/:/logs/
networks:
  hanying:
    external: true