version: '3'
services:
  #授权服务
  hanying_admin:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_admin:latest
    container_name: hanying_admin
    restart: always
    ports:
      - 8601:8601
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_admin
    volumes:
      - ../log/:/logs/
      - ../config/hanying_admin/:/config/
networks:
  hanying:
    external: true