version: '3'
services:
  #授权服务
  hanying_sms:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_sms:latest
    container_name: hanying_sms
    restart: always
    ports:
      - 8604:8604
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_sms
    volumes:
      - ../log/:/logs/
      - ../config/hanying_sms/:/config/
networks:
  hanying:
    external: true
