version: '3'
services:
  #授权服务
  hanying_search:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_search:latest
    container_name: hanying_search
    restart: always
    ports:
      - 8605:8605
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_search
    volumes:
      - ../log/:/logs/
networks:
  hanying:
    external: true