version: '3'
services:
  #授权服务
  hanying_picture:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_picture:latest
    container_name: hanying_picture
    restart: always
    ports:
      - 8602:8602
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_picture
    volumes:
      - ../log/:/logs/
      - ../config/hanying_picture/:/config/      
      - ../data/hanying_data/:/home/hanying_blog/hanying_data/
networks:
  hanying:
    external: true
