version: '3'
services:
  #授权服务
  hanying_mointor:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_monitor:latest
    container_name: hanying_monitor
    restart: always
    ports:
      - 8606:8606
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_monitor
    volumes:
      - ../log/:/logs/
      - ../config/hanying_monitor/:/config/
networks:
  hanying:
    external: true
