version: '3'
services:
  #授权服务
  hanying_web:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_web:latest
    container_name: hanying_web
    restart: always
    ports:
      - 8603:8603
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_web
    volumes:
      - ../log/:/logs/
      - ../config/hanying_web/:/config/
networks:
  hanying:
    external: true
