version: '3'
services:
  #授权服务
  hanying_gateway:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/hanying_gateway:latest
    container_name: hanying_gateway
    restart: always
    ports:
      - 8607:8607
    networks:
      - hanying
    environment:
      - COMPOSE_PROJECT_NAME=hanying_gateway
    volumes:
    - ../log/:/logs/
    - ../config/hanying_gateway/:/config/
networks:
  hanying:
    external: true
