version: '3'
services:
  #授权服务
  vue_hanying_admin:
    image: registry.cn-shenzhen.aliyuncs.com/hyblog/vue_hanying_admin:latest
    container_name: vue_hanying_admin
    restart: always
    ports:
      - 9528:80
    networks:
      - hanying
    env_file:
      - ../config/vue_hanying_admin.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_hanying_admin

networks:
  hanying:
    external: true
